name: portal_pns_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.2.1
  flutter_bloc: ^7.3.2
  intl: ^0.17.0
  lottie: ^1.2.2
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.0.15
  fluro: ^2.0.3
  dio: ^5.4.0
  get_it: ^7.6.0
  bubble_tab_indicator: ^0.1.6
  device_preview: ^0.8.0
  flutter_svg: ^0.23.0+1
  page_transition: ^1.1.4
  simple_animations: ^4.0.2
  equatable: ^2.0.5
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^12.0.4
  connectivity_plus: ^2.3.9
  geolocator: ^10.1.0
  geocoding: ^2.0.5
  shimmer: ^2.0.0
  slide_digital_clock: ^1.0.3
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.1.12
  permission_handler: ^11.0.1
  percent_indicator: ^4.2.1
  modal_bottom_sheet: ^2.0.1
  html: ^0.15.1
  cached_network_image: ^3.2.0
  month_picker_dialog: ^0.4.0
  web_socket_channel: ^2.4.0
  loader_overlay: ^3.0.3
  flutter_spinkit: ^5.2.0
  crypto: ^3.0.2
  strings: ^0.2.2
  fluttertoast: ^8.2.4
  badges: ^2.0.3
  url_launcher: ^6.1.5
  flutter_widget_from_html: ^0.8.5
  share_plus: ^4.5.3
  syncfusion_flutter_pdfviewer: ^20.3.59
  timelines: ^0.1.0
  expandable: ^5.0.1
  flutter_app_badger: ^1.5.0

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.4.0
  mocktail: ^0.2.00
  platform: ^3.1.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/lottie/
    - assets/maps_style.txt
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
